### PR TITLE
Feature/hatch eggs

### PR DESCRIPTION
**Pull request by jabbink**
**Fixed issue:** #2 

**Changes made:**

* get egg hatch results
* use longest distance egg first

### CODE REVIEW

**Comment by KyleBoyer** [comment]
Hey @jabbink,

By "use longest distance egg first", does this mean in general it will descend in order of KM of the egg? The most ideal usage for incubators is to have the Infinite(reusable) incubator with the smallest KM eggs, and have the 3 time usage incubators(disposable) with the highest KM egg. This allows for maximum usage/distance of the disposable incubator.

**Comment by KyleBoyer** [comment]
Also after getting the latest and compiling, upon running I get a stack trace like so:

Exception in thread "Thread-4" com.pokegoapi.exceptions.RemoteServerException: com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
	at com.pokegoapi.api.inventory.Hatchery.queryHatchedEggs(Hatchery.java:67)
	at ink.abb.pogo.scraper.tasks.HatchEggs.run(HatchEggs.kt:35)
	at ink.abb.pogo.scraper.Bot.task(Bot.kt:83)
	at ink.abb.pogo.scraper.Bot$run$$inlined$fixedRateTimer$lambda$lambda$2.invoke(Bot.kt:77)
	at ink.abb.pogo.scraper.Bot$run$$inlined$fixedRateTimer$lambda$lambda$2.invoke(Bot.kt:21)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
	at com.google.protobuf.InvalidProtocolBufferException.truncatedMessage(InvalidProtocolBufferException.java:82)
	at com.google.protobuf.CodedInputStream.refillBuffer(CodedInputStream.java:1062)
	at com.google.protobuf.CodedInputStream.readRawByte(CodedInputStream.java:1129)
	at com.google.protobuf.CodedInputStream.readRawVarint64SlowPath(CodedInputStream.java:780)
	at com.google.protobuf.CodedInputStream.readRawVarint64(CodedInputStream.java:772)
	at com.google.protobuf.CodedInputStream.readUInt64(CodedInputStream.java:328)
	at POGOProtos.Networking.Responses.GetHatchedEggsResponseOuterClass$GetHatchedEggsResponse.<init>(GetHatchedEggsResponseOuterClass.java:137)
	at POGOProtos.Networking.Responses.GetHatchedEggsResponseOuterClass$GetHatchedEggsResponse.<init>(GetHatchedEggsResponseOuterClass.java:75)
	at POGOProtos.Networking.Responses.GetHatchedEggsResponseOuterClass$GetHatchedEggsResponse$1.parsePartialFrom(GetHatchedEggsResponseOuterClass.java:1030)
	at POGOProtos.Networking.Responses.GetHatchedEggsResponseOuterClass$GetHatchedEggsResponse$1.parsePartialFrom(GetHatchedEggsResponseOuterClass.java:1025)
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:105)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:125)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:130)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
	at POGOProtos.Networking.Responses.GetHatchedEggsResponseOuterClass$GetHatchedEggsResponse.parseFrom(GetHatchedEggsResponseOuterClass.java:461)
	at com.pokegoapi.api.inventory.Hatchery.queryHatchedEggs(Hatchery.java:65)
	... 5 more

**Comment by jabbink** [comment]
Server offline. Retry

**Comment by KyleBoyer** [comment]
@jabbink What about in regards to the comment above the stack trace?

Side note: how can I import this project into Eclipse/IntelliJ IDEA to help contribute?

**Comment by jabbink** [comment]
Weird, sounds like the server returned 4 hatched eggs, but only 3 experience items.

Please make an issue of that on https://github.com/Grover-c13/PokeGOAPI-Java/

**Pull request merged**
