### PR TITLE
Split settings and bot code into their own classes.

### PR DESCRIPTION
**Pull request by apottere**
I took the liberty of separating the 3 components (initialization, settings, and botting) up so the code is easier to understand.

Functional changes included in this PR:
* `base64_password` setting is used if `password` is missing, allowing your password to be base64 encoded.  This doesn't mean it's secure, but at least it's not in plaintext so it can't be read over your shoulder.
* ~~Added pokemon CP transfer threshold as a setting.~~

### CODE REVIEW

**Comment by falko100** [comment]
:-1:  I don't want the pass encoded. Maybe give the option for encoded password ?

**Comment by apottere** [comment]
Yeah, I can do that.  Working through the merge conflicts right now.

**Comment by apottere** [comment]
Ok, I added a `base64_password` setting that is checked if `password` is empty.

**Comment by jabbink** [comment]
Thanks, looks good. Now I'll have to see how to efficiently merge this with the current `master` and #39 :P

**Comment by jabbink** [comment]
Should be merged in https://github.com/jabbink/PokemonGoBot/tree/pr/38-39

Can't test as the servers are offline

**Comment by apottere** [comment]
Thanks!  I can help merge stuff in too, I realize it probably caused a lot of conflicts.

**Pull request merged**
