### PR TITLE
[webUI] Complete style revamp.

### PR DESCRIPTION
**Pull request by eruecco87**
Gave the Web UI some loving, did not integrate automated build processes with gulp or bower and also did not use CSS preprocessors or SPA frameworks like Angular since this is a fairly small interface and it seemed like overkill. All third party CSS and JS is loaded from a CDN.

I've also integrated most of the functionalities that exist in other currently open pull requests about the Web UI like eggs display and pokémon IV details.

I'm not a Java guy so I hope that some of the changes I made to **WebServer.kt** are not retarded. I'm sure there is a better way of doing what I did there.

**Changes made:**

* Added Bootstrap styles for the UI.
* Extracted and Refactored CSS and Javascript.
* Created small modular architecture for components.
* Changed maps iconography.
* Re ordered UI elements in a more logical fashion.

**Need to change:**

* Better way to serve CSS and JS files, hopefully get to serve multiple files so the code can be split into separate files.

**Screen Shots:**

* New UI:
UI

* Eggs Component:
eggs

* Pokebank Component: 
pokebank

* Console Component:
console

### CODE REVIEW

**Comment by smileytechguy** [comment]
whats the advantage to bootstrap and a fixed layout?  I like the current ability to reorganize as needed

**Comment by eruecco87** [comment]
Bootstrap saves a lot at writing styles for interface elements. So panels, menus, buttons, etc. are already created and can be reused as new functionalities are added. It's great for code reuse and allows you to scale the app quickly.

The ability to reorganize the panels as needed is still there, this just looks a bit cleaner and it's not all smashed together on initial load (I saw complaints that people couldn't find the windows at first).

But this pull request most of all organises the code in a modular fashion so there's no spaghetti Javascript or a load of CSS hanging out in index.html. If I could figure out how to serve multiple js files from the Java web server this would be even more organized.

**Comment by smileytechguy** [comment]
I wasnt able to get the interface to move when i pulled this commit.  I know how it helps having a framework, and if you look at my latest PR i even used a few snippets of bootstrap's CSS for buttons.  However, I don't think it is needed to fully redesign the GUI with bootstrap.  I understand the initial layout problem, as I was confused at first too.  I think perhaps a clarification in the README or release epage would fix that

**Comment by eruecco87** [comment]
Well, If you move your focus away from the fact that the UI was redesigned. The actual code was completely refactored for the reasons explained in my posts above. 

I can't help but feel that you might be taking the re-write personal, but there was a lot of scattered javascript in the code, don't get me wrong, it was a magnificent starting point. I just tried to give it more of an application modular architecture so it can scale better as opposed to just dumping javascript functions inside a script tag.

**Here are some more additions to the UI**:

* Displays a badge for the pokémons that were caught during the session
new

* New component "Loot History"
loot

**Comment by langerhans** [comment]
Awesome work! Clashes a little with #549 . Ultimately it would be nice to be able to distribute different interfaces as independent jars so people could use the interface they want. I hope the integration of Spring gives us a lot more freedom in that regard, see #622

**Comment by kasagon** [comment]
I like how this one looks, it has a lot of information but you still can organize everything as you want.

I have a small request though, for making the page a little bit more 'alive', I have made a background-gradient a while back, based on the intro of Pokemon Sapphire ( https://youtu.be/_Riv34cwq7E?t=20s ). It has not that much detail, but it is a background and I think a background does not need to attract to much attention.

CSS:

    body {
	    background: #ACD8FB;
	    background: -webkit-linear-gradient(top, rgb(122, 185, 228) 0%, rgb(171, 214, 247) 34%, rgb(255, 255, 255) 42%, rgb(127, 161, 241) 43%, rgb(178, 222, 234) 44%, rgb(80, 127, 236) 56%, rgb(101, 131, 246) 57%, rgb(38, 69, 108) 59%, rgb(176, 224, 97) 60%, rgb(97, 171, 89) 68%, rgb(118, 165, 113) 100%);
	    background: -o-linear-gradient(top, rgb(122, 185, 228) 0%, rgb(171, 214, 247) 34%, rgb(255, 255, 255) 42%, rgb(127, 161, 241) 43%, rgb(178, 222, 234) 44%, rgb(80, 127, 236) 56%, rgb(101, 131, 246) 57%, rgb(38, 69, 108) 59%, rgb(176, 224, 97) 60%, rgb(97, 171, 89) 68%, rgb(118, 165, 113) 100%);
	    background: -ms-linear-gradient(top, rgb(122, 185, 228) 0%, rgb(171, 214, 247) 34%, rgb(255, 255, 255) 42%, rgb(127, 161, 241) 43%, rgb(178, 222, 234) 44%, rgb(80, 127, 236) 56%, rgb(101, 131, 246) 57%, rgb(38, 69, 108) 59%, rgb(176, 224, 97) 60%, rgb(97, 171, 89) 68%, rgb(118, 165, 113) 100%);
	    background: -moz-linear-gradient(top, rgb(122, 185, 228) 0%, rgb(171, 214, 247) 34%, rgb(255, 255, 255) 42%, rgb(127, 161, 241) 43%, rgb(178, 222, 234) 44%, rgb(80, 127, 236) 56%, rgb(101, 131, 246) 57%, rgb(38, 69, 108) 59%, rgb(176, 224, 97) 60%, rgb(97, 171, 89) 68%, rgb(118, 165, 113) 100%);
	    background: linear-gradient(to bottom, rgb(122, 185, 228) 0%, rgb(171, 214, 247) 34%, rgb(255, 255, 255) 42%, rgb(127, 161, 241) 43%, rgb(178, 222, 234) 44%, rgb(80, 127, 236) 56%, rgb(101, 131, 246) 57%, rgb(38, 69, 108) 59%, rgb(176, 224, 97) 60%, rgb(97, 171, 89) 68%, rgb(118, 165, 113) 100%);
	    background-attachment: fixed;	
    }

**Comment by eruecco87** [comment]
Might be that the socket server is not sending the newly caught pokemon stats or id data. Not quite sure how to fix this since I know nothing about Java.

**Comment by jabbink** [comment]
Great work, please see #728 

I'm very tempted to move the UI out of this repo and host it externally (eg GitHub Pages), that way multiple UI's can peacefully co-exist and users can pick whatever they want. For that to work we need to better define the current web socket behaviour (eg. versioned url's and UI's may request updates on specific items, so some mobile UI/app that only shows the status of your x bots wouldn't receive all map updates, and versioned, so new UI's can use newer functions while old UI's still receive the expected data)

**Comment by eruecco87** [comment]
@jabbink I saw 728 before, and that actually makes a lot of sense to me. So if I understand correctly each different UI "Theme" can live on its own repo with gh-pages and have the user select whatever they want through the config in the main Java App?

Although doing this will need for the UI's to have some way to configure custom socket ports in case the user changes them in the Java App, should be easy enough!

I will always support the idea of decoupling Front End from Back End.

**Comment by smileytechguy** [comment]
I created some documentation in #739 of how to create an independent GUI, couldnt figure out how to do a new PR so had to reuse old one

**Comment by jabbink** [comment]
>Although doing this will need for the UI's to have some way to configure custom socket ports in case the user changes them in the Java App, should be easy enough!

Yes, I currently changed the ui on that `gh-pages` branch to accept the hostname and port via the location hash (eg map.html#localhost:8001). That way it won't be transferred to the server either and stays client side.

**Comment by Magnog** [comment]
How do you view the GUI? I'm using the bot on my mac with terminal, but how do i view the GUI? is it a separate command or something? or a website?

**Comment by TheOGMrJoosh** [comment]
@Magnog type localhost:8000 into your browser, and you'll be on.

**Comment by Magnog** [comment]
@TheOGMrJoosh  Thank you that worked, also is there a way to set the bot to power up your pokemons?  i have like 13 electabuzzes, or is this feature going to be added?

**Comment by eruecco87** [comment]
Closing this PR since all indicates that UI's will become separate from the main repo.

**Comment by jabbink** [comment]
Yeah, you may do a PR to the `gh-pages` repo though. That stuff is statically hosted on pogo.abb.ink

**Pull request closed without merging**
