### PR TITLE
Re-added ban detection and added wait time as setting

### PR DESCRIPTION
**Pull request by citruz**
**Changes made:**

* Re-added ban detection because Thread.sleep() now has the desired effect since #345
* Added setting ban_wait_time to specify the number of seconds to wait after a ban has been detected

### CODE REVIEW

**Comment by muschter** [comment]
Why not do soft ban bypass?

**Comment by citruz** [comment]
How?

**Comment by EyesReye** [comment]
If you spin a Pokestop 40+ times it unbans you :)

**Comment by muschter** [comment]
@citruz Spin and close a pokestop about 40-50 times and it removes your soft ban.

**Comment by citruz** [comment]
Oh ok, didn't knew that. I will try it later ;)

**Comment by muschter** [comment]
Good luck!

**Comment by citruz** [comment]
I updated the PR to attempt a softban bypass automatically :)
Replaced `ban_wait_time ` with `ban_spin_count` which specifies the number of spins (if Niantic decides to change that). This setting can be set to 0 to disable the functionality.
By default it is enabled and set to 40.
It takes about 40*300ms = 12 sec to spin the pokestop that many times but I think this acceptable since it gives you the ability to catch pokemon and gain XP again.

**Comment by rfalkner** [comment]
How can i pull these changes?

**Comment by citruz** [comment]
`git clone https://github.com/citruz/PokemonGoBot/tree/softbanDetection`

**Comment by muschter** [comment]
@rfalkner Merge his fork's branch into your cloned repository and compile it.

**Comment by rfalkner** [comment]
Dosent work for me. I will wait until a prebuilt version is out i guess. 

Thanks for helping tho

**Comment by langerhans** [comment]
Can confirm this works. Been jumping between SF and NY back and forth and after 40 spins continued as if nothing happened.

**Comment by jabbink** [comment]
Has anyone tried putting those 40 spin requests in a single RequestEnvelope?

**Comment by Jadennapali** [comment]
Help?? 
Not the best with this kinda stuff but keep getting this " git clone https://github.com/citruz/PokemonGoBot/tree/softbanDetection
Cloning into 'softbanDetection'...
fatal: repository 'https://github.com/citruz/PokemonGoBot/tree/softbanDetection/' not found" How can I fix this

**Comment by Cypherke** [comment]
you're trying to download ("clone") a tree that has been merged with the main develop tree. This SoftbanDetection tree doesn't exist any more. You should use git clone https://github.com/jabbink/PokemonGoBot

**Comment by michaeldajnowicz** [comment]
40-50 spins to unban? maybe within doing that your time ban is up

**Comment by jabbink** [comment]
No, the time ban is minutes to hours. Spinning 40 times takes <12 seconds.

**Pull request merged**
