### PR TITLE
Change caught to collected

### PR DESCRIPTION
**Pull request by Pblolpb**
Phrasing of catching items sounds wrong. I think collecting is better.

### CODE REVIEW

**Comment by pr0ves** [comment]
Well... it's "gotta catch 'em all" not "gotta collect 'em all".

**Comment by Akkadius** [comment]
This PR is kind of ridiculous, not gonna lie

**Comment by Pblolpb** [comment]
True, when you say it that way, I guess catch does make sense.  I just wasn't sure if it was it was supposed to be catch for both the pokemon and items.

**Comment by pr0ves** [comment]
I'll close then.

**Pull request closed without merging**
