### PR TITLE
Save last location

### PR DESCRIPTION
**Pull request by Peyphour**
**Fixed issue:** #144 

**Changes made:**

* Update settings lat/lng on bot stop. JSON file will get automatically updated with the last location

### CODE REVIEW

**Comment by KyleBoyer** [comment]
This won't write out to the .properties file tho. The required function to be used is settings.writeProperty(fileName, "key", "value")

**Comment by Peyphour** [comment]
Don't know you followed one of my last PR but now all config files are JSON files.
Which means that : 
  - If you create a .properties it will be migrated to a .json on the bot shutdown
  - If you change a setting during runtime, it will thus be saved in the .json file

**Comment by AlexBoulyga** [comment]
Just a question, If you dont usw an IDE, how do you change those settings?

**Comment by AlexBoulyga** [comment]
Before i noticed that i was searching for over half an hour why the bot does not use my changes made in the config.properties

**Comment by Peyphour** [comment]
You don't need an ide to change to .json  config file

**Comment by AlexBoulyga** [comment]
OK then thats good :)

**Comment by FrancYescO** [comment]
am i wrong or this is fully useless? is saving cordinates just to a var when closing?!

probably was better implemented in https://github.com/jabbink/PokemonGoBot/pull/1130 but both have the issue https://github.com/jabbink/PokemonGoBot/issues/1142

**Comment by Peyphour** [comment]
When closing, the bot's current settings are saved to a json file. 
And when there is at least one json file, the . properties isn't loaded anymore

**Comment by Peyphour** [comment]
Did you read my answer to Kyle who asked the same thing ? ...

**Pull request merged**
