### PR TITLE
Changed CP threshold with IV percentage threshold

### PR DESCRIPTION
**Pull request by pr0ves**
Did as asked in #45

### CODE REVIEW

**Comment by jabbink** [comment]
:+1:

can you make it compatible with #69 (colors) though?

**Comment by pr0ves** [comment]
As soon as i get home.

**Comment by vohphuong** [comment]
I got when building

Cannot access 'username': it is 'private' in 'PlayerProfile'

and many lines

**Comment by pr0ves** [comment]
@pvase666 I'm fixing it right now

**Comment by pr0ves** [comment]
@pvase666 it's strange that you have that problem because username is accessed through the getter.
Also i think you should post this as issue not here, create an issue and post all of the error not just one line.

**Comment by pr0ves** [comment]
You can merge now.

**Comment by pr0ves** [comment]
Added only the count of pokemon, can't get the number of items because there's no function in Bag class to return the item list

**Comment by pr0ves** [comment]
There's a problem with the stardust, it doesn't get updated after the bot catches a pokemon.
It's probably set the first time and never updated. Is this a pokegoapi problem or ours?

**Pull request merged**
