### PR TITLE
Add color in console

### PR DESCRIPTION
**Pull request by dommerq**
Add some pretty colors so it's easier to read when you catch some pokemon (green) or when something when wrong (red)

### CODE REVIEW

**Comment by alexvndre** [comment]
👍

**Comment by apottere** [comment]
Could we use something like this instead of rolling our own log? https://github.com/Tuxdude/logback-colorizer/blob/master/README.md

**Comment by dommerq** [comment]
Looks overkill to me, I think there's too much config on this ¯\_(ツ)_/¯

**Comment by RaeneDev** [comment]
gotta make things perty. 
If nothing has been added/researched i can look into something for this in a couple hours. I was possibly thinking of making a GUI to add a launch button, change config settings, and an option to hide output such as item drops but I mostly do web languages so I'm not sure how well or even if I could do this.

**Comment by jabbink** [comment]
Too be honest, using slf4j with logback sounds better imo, but I have to agree that this is an overkill for to add now and in case we ever want to switch, replacing this with slf4j should still be easy to do.

**Comment by jabbink** [comment]
Also my console apparently doesn't get resets.

image

**Comment by dommerq** [comment]
wow that's weird. Reset works because you get the normal grey color after but I don't know what those characters are :/ 
Will look and update this PR.

**Comment by jabbink** [comment]
While you're at it, could you add logging of the time?

**Comment by jabbink** [comment]
Reset works fine in the IntelliJ console by the way.

Probably some bug with pantheon-terminal + zsh.

**Comment by dommerq** [comment]
Can't test pantheon-terminal, I'm on OSX. (using zsh on OSX, it works :/ )

I'm gonna add the time yep

**Comment by apottere** [comment]
@RaeneDev I'm looking into adding a web frontend too.

**Comment by jabbink** [comment]
Too late, but I notice the namespace of the logging thing is `Log`

Will change that tomorrow.

**Pull request merged**
