### PR TITLE
Feature force evolution

### PR DESCRIPTION
**Pull request by Orabig**
I added the possibility to automatically evolve all the low pokemons (Pidgey and al.) for a great amount of XP.
The new "obligatory_evolve" parameter takes the list of pokemon that should be evolved (if possible). If there is not enough candy left, then the pokemon is transfered instead.

### CODE REVIEW

**Comment by Orabig** [comment]
Damn ! Duplicate of #98 ?
:( I feel so stupid...

**Comment by jabbink** [comment]
Looks good, maybe combine it with a list of candy required of #98.

Also please indent with spaces (default IntelliJ indentation)

**Comment by jabbink** [comment]
Hold that thought: the API will get the candies required.

**Comment by Orabig** [comment]
Well, yes, I could use some of the #98 code, but what will be the difference ? I guess the fonctionnality is pretty much the same, so where's the point to write it on both PR ?
However, if you choose my implementation, I'll be glad to help and finish this (and use proper indentation :))

**Comment by Orabig** [comment]
Also, i guess I have to merge the 'develop' branch, and make a PR on this one...

**Comment by jabbink** [comment]
>Well, yes, I could use some of the #98 code, but what will be the difference ?

Mainly that that code doesn't try to evolve every iteration and checks before if you have enough candies

**Comment by pr0ves** [comment]
Closing this pr because wants merge with `master` branch.
Open another one asking to merge with the `develop` branch.

**Pull request closed without merging**
