### PR TITLE
Make bot a Spring Boot app (in preparation for a web frontend).

### PR DESCRIPTION
**Pull request by apottere**
- [x] Spring-Boot dependencies and annotation added.
- [x] Settings serialization/deserialization with jackson - no more reading a properties file.
- [x] Read old `config.properties` file and convert to new save file if no other bots are found.
- [x] Support for multiple bots running at the same time with their own settings.
- [x] Fix merge conflicts.
- [x] Update documentation to reflect these changes.

### CODE REVIEW

**Comment by apottere** [comment]
@jabbink This should be good to go if you want to review it.

**Comment by Ixath** [comment]
I love this. Can't wait to see some of this added. Great work.

**Comment by davidmann4** [comment]
screenshot? :) I am currious

**Comment by apottere** [comment]
No web UI yet, but this will allow me to start one.

**Comment by apottere** [comment]
@jabbink merge conflicts are resolved now.

**Comment by CptJackieSparrow** [comment]
woaaa,lets see

**Comment by apottere** [comment]
Closing to merge against `develop`.

**Pull request closed without merging**
