### PR TITLE
Map toolbar map services; documentation for future creation of GUIs

### PR DESCRIPTION
**Pull request by smileytechguy**
Adds a dropdown with links to 3 map services as well as a disabled Pokévision link (because it is down).  Also, beautifies the "map toolbar"

### CODE REVIEW

**Comment by smileytechguy** [comment]
Created a README for creating your own custom theme, and full documentation

**Comment by jabbink** [comment]
Maybe put this in the Wiki of the repo and rename this file to `README.md` and put it on the `gh-pages` branch?

**Comment by smileytechguy** [comment]
alright

**Comment by smileytechguy** [comment]
@jabbink the wiki loops back to the README.md, so put it in these?

**Comment by smileytechguy** [comment]
@jabbink done; see #753 .  I will make a PR with only https://github.com/jabbink/PokemonGoBot/pull/739/commits/7456216eb6694107d9c485dd884e835d0d758b30 this commit once #753 is merged

**Comment by jabbink** [comment]
Merged your other PR

**Pull request closed without merging**
