### PR TITLE
UI Page Revamp

### PR DESCRIPTION
**Pull request by EpicAwesomeWolf**
### Prerequisites (Remove this section if you want)
Make sure you...

* Follow the [contribution guidelines](CONTRIBUTING.md)
* Submit this PR against the `develop` branch.

**Changes made:**

* Added new UI Page

### CODE REVIEW

**Comment by smileytechguy** [comment]
screenshots?

**Comment by EpicAwesomeWolf** [comment]
@smileytechguy https://epicawesomewolf.github.io/PGOBotWebUI

**Comment by EpicAwesomeWolf** [comment]
Oops. It's https://epicawesomewolf.github.io/PGOBotUIPage

**Comment by JoeyyT** [comment]
Fix the buttons: you currently only have the text inside the buttons clickable with a <a href> you should put the <a href> infront of the button :)

**Comment by EpicAwesomeWolf** [comment]
@JoeyyT is this not right? `<a href="http://ui.pogobot.club/TTL55/"class="white-text">TTL55 - Improved Poppo</a>`

**Comment by JoeyyT** [comment]
@EpicAwesomeWolf That is right but youre making only the text clickable, start the a href infront of the button then exclude the text and end the ahref after the button, then manually add the TTL55 etc in the button field

**Comment by EpicAwesomeWolf** [comment]
@JoeyyT I still don't understand xD Just PR it to the repo and I'll add it.

**Comment by jabbink** [comment]
@EpicAwesomeWolf this happens because the `<a>` tag isn't over the entire button.

http://gfycat.com/SandyHauntingGar

**Comment by EpicAwesomeWolf** [comment]
@jabbink I'm using `<div=container>` so I think that is the problem. 
`                <div class="container">
                    <div class="row">
                        <div class="col s12">
                            <div class="btn-flat center green-moss border-green white-text waves-effect waves-green enabled fullWidth"
                                 style="width: 50%; height: 50px; line-height: 50px; button left">
                                <a class="enabled"
                                   style="color: white;">
                                <a href="http://ui.pogobot.club/0.5.0-alpha4/map.html"class="white-text">Original UI</a>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>`
I've tried putting it everywhere. I thought this looked right however but I guess not.

**Comment by EpicAwesomeWolf** [comment]
@jabbink @Sieberkev Alright, I fixed the buttons. Should be up and ready to go!

**Comment by EpicAwesomeWolf** [comment]
I believe the only conflict is that my fork was not updated with today's update, but I'll be happy to create a link or something for it.

**Comment by Sieberkev** [comment]
If you add this repo as a remote to your local repository `git remote add upstream https://github.com/jabbink/PokemonGoBot.git`, fetch the changes with `git fetch upstream` and `git merge upstream/gh-pages`, fix any merge conflicts that result from that and push the solution, the button will be green again :)

**Comment by EpicAwesomeWolf** [comment]
Weird, doesn't let me merge them. I'll just refork and send again :)

**Comment by EpicAwesomeWolf** [comment]
Alright, closing PR and reforking.

**Pull request closed without merging**
