### PR TITLE
Added maximum CP of the transferred pokemons and list of pokemons not to transfer

### PR DESCRIPTION
**Pull request by pr0ves**
As title.
Added same option as #38

### CODE REVIEW

**Comment by davidmann4** [comment]
good idea!

**Comment by Crackwizard** [comment]
very good idea

**Comment by jabbink** [comment]
Looks good, will try to merge this together with #38

**Comment by pr0ves** [comment]
Should work now.

**Comment by jabbink** [comment]
Thanks, will merge now

**Comment by jabbink** [comment]
Should be merged in https://github.com/jabbink/PokemonGoBot/tree/pr/38-39

Can't test as the servers are offline

**Pull request merged**
