### PR TITLE
Update Web UI

### PR DESCRIPTION
**Pull request by Loewe1000**
**Fixed issue:** [Reference the issue number here, or remove if not a fix]

**Changes made:**

* Deleted the box-shadow for less "fragmented feeling" of the UI.
* Added 5px padding to the log to improve readability.

### CODE REVIEW

**Comment by KyleBoyer** [comment]
I'm having a trouble with getting data back from http://localhost:8000/

I get a no response/data error in Chrome

**Comment by jabbink** [comment]
Please stay on topic

**Comment by KyleBoyer** [comment]
> Please stay on topic

Should I open a new issue in regards to the Web UI?

**Comment by Loewe1000** [comment]
This is not even an issue thread. It was an pull request. 
So if you have any problems open an issue!

**Pull request merged**
