### PR TITLE
add a multiplier to go moe often to pokestop with lure

### PR DESCRIPTION
**Pull request by Aedius**
**Changes made:**

* added a parameter to go more often to lure. By default multiplier is 1.

### CODE REVIEW

**Comment by Emuuung** [comment]
This doesn't interfere with `random_next_pokestop_selection` setting?

**Comment by Aedius** [comment]
@Emuuung no ( or i made a big mistake )
for example with lure_pokestop_modifier=2.5
i dont change the pokestop selection
just a pokestop without lure at 100step and a pokestop at 250step have the same chance of being elected

**Comment by Emuuung** [comment]
@Aedius Ah, that sounds nice, maybe you should also add an `always_move_to_lure` setting to always piroritize the pokestops with lure if timeout is over.

**Comment by Aedius** [comment]
@Emuuung i will start that :)

**Comment by alone23** [comment]
And when arrives, don't move until lure is gone?

**Comment by Aedius** [comment]
@alone23 not in this PR, maybe later ;)

**Comment by Aedius** [comment]
@Emuuung done

**Comment by Emuuung** [comment]
This look nice, I like it, One question tho, if the bot finds 2 or more pokestops with lure, how does it pick one? through distance-probability or by equal-probability?

**Comment by Aedius** [comment]
@Emuuung i sort the array by distance and pick the first. I did that because lure have a timeout, so you have to hurry.

**Comment by Emuuung** [comment]
@Aedius Oh, another thing... maybe add to log console when it's moving to a pokestop with lure. I think that would be my final suggestion :wink:

**Comment by Emuuung** [comment]
I'm testing it but it's hard to find a pokestop with lure right now, will let you know in a new edit...

**Comment by Emuuung** [comment]
Also, I get these lines of error, but no sure if it's related:
```
Error running loop WalkingLoop!
com.pokegoapi.exceptions.LoginFailedException: Error  in API Url
        at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:129)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:302)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:270)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:205)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:195)
        at com.pokegoapi.api.map.Map.getCatchablePokemon(Map.java:103)
        at ink.abb.pogo.scraper.util.map.MapKt.getCatchablePokemon(Map.kt:15)
        at ink.abb.pogo.scraper.tasks.Walk$walk$1.invoke(Walk.kt:86)
        at ink.abb.pogo.scraper.tasks.Walk$walk$1.invoke(Walk.kt:21)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:139)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:32)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
```
The bot eventually resume walking.

**Comment by Aedius** [comment]
@Emuuung i don't change to many things in log, i'm not sure if it's important to see.
The error was a login exception, nothing that i touch

**Comment by Emuuung** [comment]
@Aedius Well I guess is not really important to add, but in order to merge I guess it makes it easy for members to check logs when it is working, and letting others testing it makes it even faster.

**Comment by Aedius** [comment]
@Emuuung having lure or not doesn't matter that much, the principal point is "how much changing the parameter change the chance." and i don't know how to log it ( i'm new in this language )

**Comment by langerhans** [comment]
Played around with this and seems to work fine for me. Can you rebase and resolve the conflicts so we can merge, please?

**Comment by Aedius** [comment]
@langerhans i found an error in the develop branch : walkAndComeBack is not call

**Comment by langerhans** [comment]
That is not a problem. It was disabled cause it didn't work fully in all cases. You can ignore it for now.

**Comment by Aedius** [comment]
@langerhans i'm sure i did well, it's a lot a file change that i don't touch :s

**Comment by langerhans** [comment]
Nope, now you merged in tons of changes that are in here already. You want to checkout develop, pull, checkout your branch, rebase and then push that back here.

**Comment by Aedius** [comment]
@langerhans i did it no change ( just ~ 10 merge -_-" )

**Comment by ryangardner** [comment]
FYI: Until this PR https://github.com/Grover-c13/PokeGOAPI-Java/pull/344  (or another PR that enables lure-catching) is merged into the underlying java-API, there isn't any benefit to go to a lured pokestop because the bot wont catch any of the pokemon that are attracted by the lure 

Once the bot catches pokemon that are on lures, having it seek out lures would be a nice feature

**Comment by jabbink** [comment]
#728 updates that, or someone make a PR and take those fixes over and merge it before the entire UI thing is resolved.

**Comment by jabbink** [comment]
Please fix the merge conflicts and this should be ready to merge.

**Comment by Aedius** [comment]
@jabbink i can't dev until sunday, so i will do it on sunday

**Comment by jabbink** [comment]
That's fine.

**Comment by Aedius** [comment]
i get some trouble while merging, so i redo my dev on a clean branch so clean PR : https://github.com/jabbink/PokemonGoBot/pull/811

**Pull request closed without merging**
