### PR TITLE
dynamically load Unknown6Provider and inject values into packets

### PR DESCRIPTION
**Pull request by jabbink**
**Changes made:**

* dynamically load Unknown6Provider and inject values into packets

### CODE REVIEW

**Comment by Berni78** [comment]
Hi @jabbink ,
I tried to get the bot running with the las modifications you've made but was not successful.
Guess that I'm not loading the right jar file as the Unknown6Provide remains a ClassNotFoundException when ran.
Any help will be welcome.
Cheers,
Berni

**Comment by pirocoptero** [comment]
Hey @jabbink, 
Can you explain about this Unknown6Provide?? 
What's the path for this? 

# path to jar that includes a Unknown6Provider class with function

Thanks buddy!

**Comment by benniblau** [comment]
https://github.com/keyphact/pgoapi

**Comment by akocmark** [comment]
@jabbink hey man, great work of you! I wonder when can we expect an ETA? necro and all other bots are working fine at the moment.

Cheers

**Comment by langerhans** [comment]
Asking for ETAs is generally considered rude, folks. There is a working impl now, we'll check it out asap. Please just be patient a little longer ;)

**Pull request merged**
