### PR TITLE
Pokeball ordering

### PR DESCRIPTION
**Pull request by mmastika**
Overriding pokeball choice for individual pokemons.

When the choice isn't available in the bag, it will attempt to find first available pokeballs, in decreasing order of "effectiveness"

### CODE REVIEW

**Comment by jabbink** [comment]
I think the idea was to find a "formula" to calculate the required pokeball (and whether or not to use a razz berry)

**Comment by jabbink** [comment]
See #34

**Comment by jabbink** [comment]
EncounterResponse has a list of `CaptureProbability`s per pokeball

**Comment by mmastika** [comment]
I hear you, ideally yeah.  I'm guessing it'd be a function of rarity (pokemon_id), cp and iv. This patch would allow some degree of customisation for the first one, which is lacking at the moment.

**Comment by pr0ves** [comment]
Closing this pr because wants merge with `master` branch.
Open another one asking to merge with the `develop` branch.

**Pull request closed without merging**
