### PR TITLE
Fix Division by Zero error

### PR DESCRIPTION
**Pull request by muschter**
This fixes a division by zero error with evolving Pokemon.

**Fixed issue:** #1147 

**Changes made:**

* Check to see if the number of candies is greater than zero

### CODE REVIEW

**Comment by Sieberkev** [comment]
Can you update with base branch please? :D

**Comment by muschter** [comment]
@Sieberkev Done.

**Comment by Sieberkev** [comment]
Thank you for your contribution!

**Comment by muschter** [comment]
No problem.

**Pull request merged**
