### PR TITLE
Brighter colors for better readability

### PR DESCRIPTION
**Pull request by Darakath**

### CODE REVIEW

**Comment by jabbink** [comment]
Can you add comparison screenshots?

**Comment by CosmoRing** [comment]
image

**Comment by MASSV** [comment]
Worth noting too is colors seem to be effected by settings for terminal/console. Colors for me are not the same on Windows CMD.

**Comment by classicalDonkey** [comment]
Can we have different colours for different things?  I like that something are highlighted now, but we like have a different colour for Hatching, Looting, Caught etc

**Pull request merged**
