### PR TITLE
Changed walk_only to be more flexible

### PR DESCRIPTION
**Pull request by CosmoRing**
**Fixed issue:** #316

**Changes made:**

* Removed `walk_only`
* Added `loot_pokestop` (true/false)
* Added `catch_pokemon` (true/false)
* Added `auto_fill_incubator` (true/false)

Now you can config what you want the bot to do. Ex: The old walk only is all false except for `auto_fill_incubator`.

### CODE REVIEW

**Comment by jabbink** [comment]
Please rebase to current `develop` (so that it stays a single commit)

**Comment by jabbink** [comment]
Travis, please...

**Comment by Leodenact** [comment]
@jabbink 
Added loot_pokestop (true/false)
Added catch_pokemon (true/false)
Added auto_fill_incubator (true/false)

My bot is already catching some pokemons. but if I get this will it catch more pokemons, or whats the difference`
What happens if I put false on loot pokestops and I run out on balls?

**Comment by jabbink** [comment]
>What happens if I put false on loot pokestops and I run out on balls?

It will start to only walk around and hatch eggs.

**Pull request merged**
