### PR TITLE
implement setlocation in REST api

### PR DESCRIPTION
**Pull request by FrancYescO**
Fixing https://github.com/jabbink/PokemonGoBot/pull/952/commits/f460c73414b6ac54bee518abdeb8016997eac839

just taken the code from socketserver

### CODE REVIEW

**Comment by Peyphour** [comment]
Thanks !

**Comment by Peyphour** [comment]
But is it possible to set really the bot location and not add a location to go to ?

**Comment by FrancYescO** [comment]
theoretically

ctx.pauseWalking.set(true) //hopefull it's enought to completely stop the walk
ctx.lat.set(...)
ctx.lng.set(...)
ctx.pauseWalking.set(false)

should do the teleport trick

**Comment by Peyphour** [comment]
Wasn't what I did ?

**Comment by FrancYescO** [comment]
lOl

so the issue is pauseWalking, it pauses the walk and does not stop it, it's a bit tricky with the actual code to do a teleport

the easies way is to export the local `remainingSteps` value of `walkPath` func end set it to 0 before `ctx.pauseWalking.set(false)`

**Pull request merged**
