### PR TITLE
Added kiddy bumper to front page.

### PR DESCRIPTION
**Pull request by Agronis**
Changes are to that of the Front page.

Adding a buffer of READ THIS FIRST

### CODE REVIEW

**Comment by rirze** [comment]
Nice! Could you also add the java1.8 requirement to the directions for compiling from source (this took me a while to figure out when I was building)

**Comment by Agronis** [comment]
I feel like if you're compiling from source - you're aware of what you're doing.

Otherwise, why not just use the jar release?

**Comment by rirze** [comment]
It's nice to list dependencies without expecting people to know what to have before building. Regardless, it's just a tiny point, feel free to disregard.

**Comment by Agronis** [comment]
Not disregarding.. I'll be sure to break it down soon.

**Pull request merged**
