### PR TITLE
Fix/Update configuration templates

### PR DESCRIPTION
**Pull request by Sieberkev**
**Fixed issue:** #1085 #1055 [commit msg](https://github.com/jabbink/PokemonGoBot/commit/fd1b1f059480f859210a0b08aa2f5d0fd98feeba#commitcomment-18641949)

**Changes made:**

* Add missing config keys to JSON template
* Add missing "=" to config.properties template

### CODE REVIEW

**Comment by AlexBoulyga** [comment]
hmm I hope i dont have merge problems with you as i also fixed the json file in my last commit..

**Comment by AlexBoulyga** [comment]
Semms OK, luckily (for me) only a few rows were affected

**Comment by Sieberkev** [comment]
Ah sorry my bad, i wanted to try and merge a PR for the first time with a very simple PR ^_^

Didn't see you made the fix in a PR of your own :$

**Comment by AlexBoulyga** [comment]
No problems :) first come first serve haha

**Pull request merged**
