### PR TITLE
Add proxy support

### PR DESCRIPTION
**Pull request by Peyphour**
**Fixed issue:** #997 

**Changes made:**

* Added proxy support through setting file. No need for JVM options anymore
* Only support HTTP proxy for the moment

### CODE REVIEW

**Comment by Peyphour** [comment]
Test successful, ready to merge

**Comment by request92** [comment]
This development interests me.

But can you add user and password for proxy connexion ?

**Comment by swtrpeter** [comment]
Awesome ! ! Thanks @Peyphour ! Hope this gets added in very soon !

**Comment by Peyphour** [comment]
This will not work, I just noticed that I spelled wrong the header name for authentication

**Comment by request92** [comment]
Awesome, thx a lot

**Pull request merged**
