### PR TITLE
Merge #38 and #39

### PR DESCRIPTION
**Pull request by jabbink**
Attempts to merge the refacotr of #38 and the pokemon transfer policy of #39 

@apottere and @pr0ves, please confirm that this is working.

### CODE REVIEW

**Comment by pr0ves** [comment]
Looks like it works, it moved a little bit around, but there are many RemoteServerException, surely because the servers are down

**Comment by pr0ves** [comment]
Can you add my last commit from #39? I merged with pr/38-39 and just modified the explanation of ignoredPokemon

**Comment by jabbink** [comment]
Done

**Comment by jabbink** [comment]
Seems to work, will let this run for ~15 more minutes and then merge.

**Pull request merged**
