### PR TITLE
Check LevelUp rewards & Badges

### PR DESCRIPTION
**Pull request by Sieberkev**
**Fixed issue:** Check if there are level and/or badges rewards to claim

**Changes made:**

* Check LevelUpRewards & Badges

This needs some reviewing and testing :smile:

### CODE REVIEW

**Comment by nhodges** [comment]
Is this a UI-only issue? The rewards aren't automatically distributed as you level up? (Does the bot miss all the lures/incubators as it levels up?)

**Comment by Sieberkev** [comment]
> Does the bot miss all the lures/incubators as it levels up?
At this moment, it does... This PR is to fix that :)

**Comment by jabbink** [comment]
Is there a way to request until which level these were requested already?

If not, how does the app request these upgrades? Seems like a dead-giveaway for botting that we request this every time we log in.

**Comment by Sieberkev** [comment]
I did not find such a request in the API :(

**Comment by AlexBoulyga** [comment]
I habe Götzen for my bot lvl 18 all items since lvl 2 after starting the bot implemeting the code from Here.

**Pull request merged**
