### PR TITLE
Clean up many things to prepare for 0.4.3 release

### PR DESCRIPTION
**Pull request by jabbink**
**Changes made:**

* Fix typos in contribution guidelines/readme
* Update readme (Lombok plugin; known issues)
* Request java version and OS in issue template
* Update api dep
* revert to api method to determine if incubator/egg combo is free

### CODE REVIEW

**Comment by jabbink** [comment]
Feel free to run this (make sure you do `git submodule update --init`) for as long as possible with Google and PTC and report back.

**Comment by Evuse** [comment]
Can't wait for it. Can you include all the past customizations? Like web interface, egg hatching fix, auto evolve etc? Please :)

**Comment by jabbink** [comment]
Web interface and auto evolve are not included, as they are not done.

**Comment by Leodenact** [comment]
When do you think autoevolve will be done? Maybe an idea to start saving up some 12candies-pokemon to have them ready to evolve ;)

**Comment by citruz** [comment]
I get `26 Jul 18:54:59: Failed to put egg in incubator; error: ERROR_INCUBATOR_ALREADY_IN_USE`

**Comment by Emuuung** [comment]
Can't build this PR in develop branch, log:
```
c:\PokemonGoBot>git submodule update --init
Submodule path 'lib/PokeGOAPI-Java': checked out 'ee28406d5a0f87dc2b16429f7b19e31fbac30a95'

c:\PokemonGoBot>gradlew --refresh-dependencies clean build
:clean UP-TO-DATE
:PokeGOAPI-Java:clean
:PokeGOAPI-Java:extractIncludeProto
:PokeGOAPI-Java:extractProto UP-TO-DATE
:PokeGOAPI-Java:generateProto
:PokeGOAPI-Java:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.7
C:\PokemonGoBot\lib\PokeGOAPI-Java\src\main\java\com\pokegoapi\api\map\pokemon\CatchablePokemon.java:386: error: cannot find symbol
                                .setSpawnPointId(this.getSpawnPointId())
                                ^
  symbol:   method setSpawnPointId(String)
  location: class Builder
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
:PokeGOAPI-Java:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':PokeGOAPI-Java:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

**Comment by citruz** [comment]
You need to use `git submodule update --init --recursive` instead of `git submodule update --init` ;)

**Pull request merged**
